### ISSUE TITLE
problem using on mac?

### ISSUE THREAD

**Issue by OmarGC** [ebellocchia/py_crypto_hd_wallet#20]
Good day I hope not to disturb but I tried the library and it sends me an error:
`Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from py_crypto_hd_wallet import HdWalletBipFactory, HdWalletBip44Coins, HdWalletBip49Coins
  File "/Users/omarcortes/code/python/hdwallets/venv/lib/python3.8/site-packages/py_crypto_hd_wallet/__init__.py", line 4, in <module>
    from py_crypto_hd_wallet.bip import (
  File "/Users/omarcortes/code/python/hdwallets/venv/lib/python3.8/site-packages/py_crypto_hd_wallet/bip/__init__.py", line 1, in <module>
    from py_crypto_hd_wallet.bip.hd_wallet_bip_enum import (
  File "/Users/omarcortes/code/python/hdwallets/venv/lib/python3.8/site-packages/py_crypto_hd_wallet/bip/hd_wallet_bip_enum.py", line 25, in <module>
    from bip_utils import Bip39WordsNum, Bip39Languages, Bip44Changes, Bip44Coins, Bip49Coins, Bip84Coins
  File "/Users/omarcortes/code/python/hdwallets/venv/lib/python3.8/site-packages/bip_utils/__init__.py", line 21, in <module>
    from bip_utils.wif import WifPubKeyModes, WifDecoder, WifEncoder
  File "/Users/omarcortes/code/python/hdwallets/venv/lib/python3.8/site-packages/bip_utils/wif/__init__.py", line 1, in <module>
    from bip_utils.wif.wif import WifPubKeyModes, WifDecoder, WifEncoder
  File "/Users/omarcortes/code/python/hdwallets/venv/lib/python3.8/site-packages/bip_utils/wif/wif.py", line 28, in <module>
    from bip_utils.ecc import IPrivateKey, Secp256k1PrivateKey
  File "/Users/omarcortes/code/python/hdwallets/venv/lib/python3.8/site-packages/bip_utils/ecc/__init__.py", line 2, in <module>
    from bip_utils.ecc.elliptic_curve_getter import EllipticCurveGetter
  File "/Users/omarcortes/code/python/hdwallets/venv/lib/python3.8/site-packages/bip_utils/ecc/elliptic_curve_getter.py", line 31, in <module>
    from bip_utils.ecc.secp256k1 import Secp256k1
  File "/Users/omarcortes/code/python/hdwallets/venv/lib/python3.8/site-packages/bip_utils/ecc/secp256k1.py", line 39, in <module>
    from bip_utils.ecc.secp256k1_keys_coincurve import (
  File "/Users/omarcortes/code/python/hdwallets/venv/lib/python3.8/site-packages/bip_utils/ecc/secp256k1_keys_coincurve.py", line 25, in <module>
    import coincurve
  File "/Users/omarcortes/code/python/hdwallets/venv/lib/python3.8/site-packages/coincurve/__init__.py", line 1, in <module>
    from coincurve.context import GLOBAL_CONTEXT, Context
  File "/Users/omarcortes/code/python/hdwallets/venv/lib/python3.8/site-packages/coincurve/context.py", line 4, in <module>
    from coincurve.flags import CONTEXT_ALL, CONTEXT_FLAGS
  File "/Users/omarcortes/code/python/hdwallets/venv/lib/python3.8/site-packages/coincurve/flags.py", line 1, in <module>
    from ._libsecp256k1 import lib
ImportError: dlopen(/Users/omarcortes/code/python/hdwallets/venv/lib/python3.8/site-packages/coincurve/_libsecp256k1.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_secp256k1_nonce_function_default'`

(I'm from mac monterrey)
just try the first example

**Comment by ebellocchia** [comment]
Hi,
yes I'm aware of it, that's an issue of the coincurve library. You should install bip_utils without coincurve:

    pip install bip_utils --install-option="--coincurve=0"

Regards,
Emanuele

**Comment by OmarGC** [comment]
That fixed it, thank you very much!
